### ISSUE TITLE
Slack does not replies `token_type`

### ISSUE THREAD

**Issue by jkugiya** [chaabaj/openid-scala#1]
According to [RFC](https://tools.ietf.org/html/rfc6749#section-5.1), endpoint of OAuth must reply with `token_type` parameter. But slack does not follow RFC.

**Comment by jkugiya** [comment]
```
spray.json.DeserializationException: Object is missing required member 'token_type'
[info]  at spray.json.package$.deserializationError(package.scala:23)
[info]  at spray.json.ProductFormats$class.fromField(ProductFormats.scala:60)
[info]  at com.github.chaabaj.openid.oauth.OAuthResponseFormat$.fromField(OAuthResponseFormat.scala:15)
[info]  at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:131)
[info]  at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:118)
[info]  at spray.json.JsValue.convertTo(JsValue.scala:31)
[info]  at com.github.chaabaj.openid.apis.slack.SlackOAuthService$$anonfun$issueOAuthToken$3.apply(SlackOAuthService.scala:39)
[info]  at com.github.chaabaj.openid.apis.slack.SlackOAuthService$$anonfun$issueOAuthToken$3.apply(SlackOAuthService.scala:39)
```

**Comment by chaabaj** [comment]
Thanks for noticing it. I had some doubt about slack, i think fill it with a empty string since it's a special case from slack not following the RFC.
